apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoringapp
spec:
  template:
    spec:
      containers:
      - name: monitoringapp
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
